image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2417.64164,    0.     ,  665.97156,
            0.     , 2414.80928,  432.37736,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.104379, 0.445936, -0.015993, -0.005342, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2413.29346,    0.     ,  661.72728,    0.     ,
            0.     , 2397.58252,  424.13713,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]